### ISSUE TITLE
Value Error: Not Enough Image Data

### ISSUE THREAD

**Issue by iamsunwei** [tientruongwork/E7RefreshShopTool#1]
I'm having an issue where after setting up everything, it's throwing this at me:

```
Auto refresh shop started
Working on flow [1] Started new flow
Working on flow [1] Scanning for item
Working on flow [1] Capturing in game screen
Traceback (most recent call last):
  File "C:\Users\chipp\Desktop\E7shop\/scripts/main.py", line 47, in <module>
    main()
  File "C:\Users\chipp\Desktop\E7shop\/scripts/main.py", line 41, in main
    refresh_shop_flow()
  File "C:\Users\chipp\Desktop\E7shop\/scripts/main.py", line 28, in refresh_shop_flow
    scan_for_items(False)
  File "C:\Users\chipp\Desktop\E7shop\scripts\scan_for_items.py", line 22, in scan_for_items
    boxes = capture()
            ^^^^^^^^^
  File "C:\Users\chipp\Desktop\E7shop\scripts\capture.py", line 43, in capture
    capture_handler()
  File "C:\Users\chipp\Desktop\E7shop\scripts\capture.py", line 27, in capture_handler
    im = Image.frombuffer(
         ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 3027, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 2969, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 830, in frombytes
    raise ValueError(msg)
ValueError: not enough image data
```

**Comment by tientruongwork** [comment]
Hi Sunwei, have no idea the problem you facing. Sorry couldn't help you with that.
